FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
COPY backend/package.json backend/bun.lock* ./
RUN bun install --frozen-lockfile || bun install

# Copy source code & database schema
COPY backend/ ./
RUN bunx prisma generate

EXPOSE 8080

CMD ["bun", "run", "src/index.ts"]
